version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/code/src
      - ./pyproject.toml:/code/pyproject.toml
    ports:
      - 8000:8000
