version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./rps:/code/rps
      - ./tests:/code/tests
      - ./pyproject.toml:/code/pyproject.toml
    ports:
      - 8000:8000
