name: CI
on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@master

    - name: Run tests
      run: make tests

    - name: Run lint
      run: make lint

